name: CI

on:
  push:
    branches: [ "master" ]

jobs:

  test:

    runs-on: ubuntu-latest
    
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: npm install
    
    - name: Create DB
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -prootpassword < sql/db-setup.sql
      
    - name: Run Tests
      run: npm test
